// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQgI6RTUTu3LNpspZhFwVV3vdefmCwdDM',
    appId: '1:974695670355:web:00b6a8e7b4ccfc68dd9ca6',
    messagingSenderId: '974695670355',
    projectId: 'chatbot-imc-app',
    authDomain: 'chatbot-imc-app.firebaseapp.com',
    storageBucket: 'chatbot-imc-app.firebasestorage.app',
    measurementId: 'G-3G6MM7V2CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqLVDl3-3tOo3Bwfqayv0mh2KkTrlpV7M',
    appId: '1:974695670355:android:f3fe0314a1ffcdc0dd9ca6',
    messagingSenderId: '974695670355',
    projectId: 'chatbot-imc-app',
    storageBucket: 'chatbot-imc-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9qPHV9oRexnZfQ9aJcRqD-9I1T6fRZTQ',
    appId: '1:974695670355:ios:aa5a64ee092d4ef7dd9ca6',
    messagingSenderId: '974695670355',
    projectId: 'chatbot-imc-app',
    storageBucket: 'chatbot-imc-app.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9qPHV9oRexnZfQ9aJcRqD-9I1T6fRZTQ',
    appId: '1:974695670355:ios:aa5a64ee092d4ef7dd9ca6',
    messagingSenderId: '974695670355',
    projectId: 'chatbot-imc-app',
    storageBucket: 'chatbot-imc-app.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQgI6RTUTu3LNpspZhFwVV3vdefmCwdDM',
    appId: '1:974695670355:web:bdfbe742549de33edd9ca6',
    messagingSenderId: '974695670355',
    projectId: 'chatbot-imc-app',
    authDomain: 'chatbot-imc-app.firebaseapp.com',
    storageBucket: 'chatbot-imc-app.firebasestorage.app',
    measurementId: 'G-K40571SVWK',
  );
}
